[0m22:03:41.641703 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a2b170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a9ba40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a9b5f0>]}


============================== 22:03:41.644503 | e3cfb008-321c-4be6-aeaf-97a49c335121 ==============================
[0m22:03:41.644503 [info ] [MainThread]: Running with dbt=1.10.2
[0m22:03:41.644784 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/steven/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt build', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:03:41.645064 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/steven/Documents/00_DATA LEARNING/006_GCP_Project/PROJECT1_COVID-19_LOCAL_GIT_REPO/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:03:41.646704 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.048320834, "process_in_blocks": "0", "process_kernel_time": 0.121779, "process_mem_max_rss": "107249664", "process_out_blocks": "0", "process_user_time": 0.684626}
[0m22:03:41.646900 [debug] [MainThread]: Command `dbt build` failed at 22:03:41.646861 after 0.05 seconds
[0m22:03:41.647067 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a78410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a9b7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a9b8c0>]}
[0m22:03:41.647214 [debug] [MainThread]: Flushing usage events
[0m22:03:42.048370 [debug] [MainThread]: An error was encountered while trying to flush usage events
